include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    no_implicit_dynamic_parameter: false

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
