name: spenn
description: A Dart SDK for the SPENN Business Partner API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  meta: ^1.7.0
  mocktail: ^0.1.4
  test: ^1.17.0
  very_good_analysis: ^2.1.0

dependencies:
  dio: ^4.0.0
  equatable: ^2.0.3
